import type { Metadata } from "next";
import { Mountains_of_Christmas } from "next/font/google";
// @ts-ignore: CSS module declaration not found in current TypeScript setup
import "./globals.css";
import { Providers } from "./providers";
import MobileWarningPopup from "@/components/atoms/MobileWarningPopup";
import BetaBanner from "@/components/atoms/BetaBanner";

const mountainsOfChristmas = Mountains_of_Christmas({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-mountains-of-christmas",
  display: "swap",
});

export const metadata: Metadata = {
  title: "The Donovan's Piano Room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={mountainsOfChristmas.variable}>
      <body>
        <Providers>
          <BetaBanner />
          {children}
          <MobileWarningPopup />
        </Providers>
      </body>
    </html>
  );
}