import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import MobileWarningPopup from "@/components/atoms/MobileWarningPopup";

export const metadata: Metadata = {
  title: "The Donovan's Piano Room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Import Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Mountains+of+Christmas:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>
          {children}
          <MobileWarningPopup />
        </Providers>
      </body>
    </html>
  );
}